[workspace]
members = ["crates/apps/*", "crates/libs/*"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.97"
license = "MIT OR Apache-2.0"
repository = "https://github.com/tascarrel/tascarrel"

[workspace.dependencies]
async-trait = "0.1"
base64 = "0.22"
bytes = "1"
cc = "1.2.67"
clap = "4.5"
flate2 = "1.1"
futures-core = "0.3"
futures-util = "0.3"
globset = { version = "0.4.19", default-features = false }
http-body-util = "0.1"
hyper = { version = "1", features = ["client", "http1", "server"] }
hyper-util = { version = "0.1", features = ["tokio"] }
hickory-proto = "0.26.1"
hickory-resolver = "0.26.1"
jiff = { version = "0.2", features = ["serde"] }
libc = "0.2"
nix = "0.30"
notify = "8.2"
rand = "0.9"
reportify = "0.2.2"
reqwest = { version = "0.12", default-features = false, features = [
    "rustls-tls",
    "stream",
] }
rustix = "1.0"
serde = "1"
serde_ignored = "0.1"
serde_json = "1"
sha2 = "0.10"
sysinfo = { version = "0.37", default-features = false }
tar = "0.4"
tempfile = "3"
thiserror = "2.0"
tokio = "1.45.1"
tokio-rusqlite = { version = "0.7", features = ["bundled"] }
tokio-util = "0.7"
tracing = "0.1"
tracing-subscriber = "0.3"
uuid = { version = "1", features = ["v4"] }
vte = "0.15"
vt100 = "0.16.2"
tascarrel-api = { path = "crates/libs/tascarrel-api" }
tascarrel-git = { path = "crates/libs/tascarrel-git" }
tascarrel-mux = { path = "crates/libs/tascarrel-mux" }
tascarrel-protocol = { path = "crates/libs/tascarrel-protocol" }

[workspace.lints.rust]
unsafe_code = "deny"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }

[profile.release]
lto = "thin"
strip = "symbols"
