//! Guest-side pod management, process supervision, and protocol services.

mod control_plane;
mod repositories;
mod runtime;
mod services;
mod storage;
mod usb;
mod workspace_config;

pub use control_plane::GuestControlService;
pub use control_plane::GuestControlServiceConfig;
pub use control_plane::GuestControlServiceError;
pub use control_plane::GuestServices;
pub use control_plane::GuestState;
pub use repositories::GuestRepositoryManager;
pub use repositories::PodGitError;
pub use repositories::RepositoryConfigProvider;
pub use repositories::RepositoryConfigSnapshot;
pub use runtime::network::BUILD_NETWORK_NAMESPACE;
pub use runtime::network::NetworkError;
pub use runtime::network::NetworkManager;
pub use runtime::network::PodNetwork;
pub use runtime::pod::PodId as RuntimePodId;
pub use runtime::pod::PodPolicy;
pub use runtime::pod::PodPrograms;
pub use runtime::pod::PodShare;
pub use runtime::pod::RuntimeError as PodRuntimeError;
pub use runtime::process::Executor;
pub use services::changes::ChangesService;
pub use services::changes::ChangesServiceConfig;
pub use services::changes::ChangesServiceError;
pub use services::chats::ChatEngineError;
pub use services::chats::ChatService;
pub use services::chats::ChatServiceError;
pub use services::code::CODE_EDITOR_CACHE_NAME;
pub use services::code::CODE_EDITOR_PROFILE_PATH;
pub use services::code::CodeService;
pub use services::code::CodeServiceConfig;
pub use services::code::CodeServiceError;
pub use services::files::FileRead;
pub use services::files::FilesService;
pub use services::files::FilesServiceError;
pub use services::guest::GuestService;
pub use services::guest::GuestServiceConfig;
pub use services::guest::GuestServiceError;
pub use services::images::ImageBuildError;
pub use services::images::ImageBuildLimits;
pub use services::images::ImageBuildOutcome;
pub use services::images::ImageBuilder;
pub use services::images::ImageBuilderConfig;
pub use services::images::ImageInputRefresh;
pub use services::images::ImageService;
pub use services::images::ImageServiceConfig;
pub use services::images::ImageServiceError;
pub use services::images::cleanup_stale_image_build_directories;
pub use services::network::GuestNetworkService;
pub use services::network::GuestNetworkServiceConfig;
pub use services::network::GuestNetworkServiceError;
pub use services::network::NetworkBinding;
pub use services::network::NetworkFirewall;
pub use services::network::NetworkFirewallError;
pub use services::pods::PodControlConnection;
pub use services::pods::PodInitStep;
pub use services::pods::PodInitStepError;
pub use services::pods::PodService;
pub use services::pods::PodServiceConfig;
pub use services::pods::PodServiceError;
pub use services::pods::PreparedPodShareOverlay;
pub use services::pods::RuncConfig;
pub use services::pods::ShareOverlay;
pub use services::pods::ShareOverlayRuntimeConfig;
pub use services::pods::WorkspaceCaConfig;
pub use services::processes::ProcessSupervisor;
pub use services::processes::ProcessSupervisorConfig;
pub use services::processes::ProcessSupervisorError;
pub use storage::ChatStorage;
pub use storage::Database;
pub use storage::DatabaseError;
pub use storage::GuestStorage;
pub use storage::GuestStorageConfig;
pub use storage::GuestStorageError;
pub use storage::InputStorage;
pub use storage::NetworkStorage;
pub use storage::NixStoreStorage;
pub use storage::RepositoryStorage;
pub use storage::ScratchStorage;
pub use usb::UsbGuest;
pub use workspace_config::WorkspaceCache;
pub use workspace_config::WorkspaceCodeEditor;
pub use workspace_config::WorkspaceConfig;
pub use workspace_config::WorkspaceEditors;
pub use workspace_config::WorkspaceFeatures;
pub use workspace_config::WorkspaceInit;
pub use workspace_config::WorkspaceInitStep;
pub use workspace_config::WorkspaceNetwork;
pub use workspace_config::WorkspaceNix;
pub use workspace_config::WorkspaceRepository;
pub use workspace_config::WorkspaceSetup;
pub use workspace_config::WorkspaceSetupStep;
pub use workspace_config::WorkspaceVm;

/// Name assigned to the virtio-serial port by QEMU.
pub const VIRTIO_PORT_NAME: &str = "tascarrel-control";

/// Default path exposed by the Linux virtio-console driver.
pub const DEFAULT_DEVICE_PATH: &str = "/dev/virtio-ports/tascarrel-control";
