[package]
name = "tascarrel-cli"
description = "Command-line client for Tascarrel"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "tascarrel"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.40", features = ["derive", "env"] }
fs2 = "0.4.3"
nix = { version = "0.30.1", features = ["user"] }
reportify.workspace = true
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.140"
sha2 = "0.10"
tar = "0.4"
tokio = { version = "1.45.1", features = ["io-std", "io-util", "macros", "net", "process", "rt-multi-thread", "signal", "sync", "time"] }
tascarrel-host = { path = "../../libs/tascarrel-hostd" }
tascarrel-api.workspace = true
tascarrel-protocol = { path = "../../libs/tascarrel-protocol" }
tascarrel-vm = { path = "../../libs/tascarrel-vm" }
xz2 = "0.1"

[build-dependencies]
cc.workspace = true

[dev-dependencies]
tempfile = "3.20"

[lints]
workspace = true
