use tascarrel_api::with_guestd_operations;
use tascarrel_api::with_hostd_operations;

fn ts_path(path: &str) -> String {
    path.split("::")
        .map(str::trim)
        .collect::<Vec<_>>()
        .join(".")
}

fn main() {
    println!("// This file is automatically generated.");
    println!("// Do not edit this file manually.\n");
    println!("import * as types from \"./generated/index.ts\";\n");

    println!("export type HostActions = {{");
    macro_rules! print_actions {
        ($(($name:literal, $input:path, $output:path),)*) => {
            $(
                println!(
                    "  {}: {{ input: types.{}; output: types.{} }};",
                    stringify!($name),
                    ts_path(stringify!($input)),
                    ts_path(stringify!($output)),
                );
            )*
        };
    }
    with_hostd_operations!(actions => print_actions);
    println!("}};\n\nexport type GuestActions = {{");
    with_guestd_operations!(actions => print_actions);
    println!("}};\n\nexport type HostSubscriptions = {{");
    macro_rules! print_subscriptions {
        ($(($name:literal, $input:path, $output:path),)*) => {
            $(
                println!(
                    "  {}: {{ input: types.{}; output: types.{} }};",
                    stringify!($name),
                    ts_path(stringify!($input)),
                    ts_path(stringify!($output)),
                );
            )*
        };
    }
    with_hostd_operations!(subscriptions => print_subscriptions);
    println!("}};\n\nexport type GuestSubscriptions = {{");
    with_guestd_operations!(subscriptions => print_subscriptions);
    println!("}};");
}
